name: "Code Analysis"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '17 4 * * 3'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        languages: ['java']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 18

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.languages }}

      - name: Build project
        run: ./gradlew --no-daemon clean build jlink

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
