name: "Code Analysis"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '17 4 * * 3'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        languages: ['java']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.1.0

      - name: Configure Java
        uses: actions/setup-java@v3.5.1
        with:
          distribution: 'temurin'
          java-version: |
            19
            17

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.languages }}

      - name: Build Application
        uses: gradle/gradle-build-action@v2.3.2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' }}
          gradle-version: '7.5.1'
          gradle-home-cache-cleanup: true
          arguments: >
            build --console plain --info --no-daemon --rerun-tasks --no-build-cache
            -Dorg.gradle.java.installations.auto-detect=true
            -Dorg.gradle.java.installations.auto-download=false

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
